dist: trusty
sudo: false

cache:
  directories:
    - fixtures/elm-stuff/build-artifacts

language: node_js
node_js:
  - "node"

env:
  matrix:
    - ELM_VERSION=0.17.1
    - ELM_VERSION=0.18.0

before_install:
  # Don't create a lock file in order to work around:
  # https://github.com/npm/npm/issues/16987
  - npm install elm@$ELM_VERSION --no-shrinkwrap

before_script:
  - npm install -g npm-install-peers
  - npm-install-peers
  - ./node_modules/.bin/elm-repl --version
  - cd fixtures
    && ../node_modules/.bin/elm-package install -y
    && ../node_modules/.bin/elm-make *.elm  --yes --output /dev/null

script:
  - npm test

notifications:
  email: false
